name: Hot News Crawler

on:
  schedule:
    # 您的定时运行设置
    - cron: '30 0 * * *'   # 北京时间 08:30
    - cron: '30 4 * * *'   # 北京时间 12:30
    - cron: '30 13 * * *'  # 北京时间 21:30
  workflow_dispatch:

# 保留您的权限设置
permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # --- 这里是唯一的修改点 ---
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        # 从 requirements.txt 文件安装所有依赖 (包括 requests, pytz, 和 feedgen)
        pip install -r requirements.txt
    
    # 保留您的“创建文件”步骤
    - name: Create frequency_words.txt if not exists
      run: |
        if [ ! -f frequency_words.txt ]; then
          echo "Creating empty frequency_words.txt file"
          touch frequency_words.txt
        fi
    
    # 保留您的“运行爬虫”步骤和所有的环境变量
    - name: Run crawler
      env:
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        WEWORK_WEBHOOK_URL: ${{ secrets.WEWORK_WEBHOOK_URL }}
        GITHUB_ACTIONS: true
      run: python main.py
    
    # 保留您的“提交和推送”步骤
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update by GitHub Actions at $(TZ=Asia/Shanghai date)" && git push)
